name: RDC Android Native App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: RDC Native App Android
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: mvn test -Dtest=AndroidNativeAppTest -X
    - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: Screenshot.png
          retention-days: 5
